-- Add onboarding fields to vendors table
ALTER TABLE vendors
ADD COLUMN IF NOT EXISTS contact_name TEXT,
ADD COLUMN IF NOT EXISTS contact_email TEXT,
ADD COLUMN IF NOT EXISTS phone TEXT,
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS website TEXT,
ADD COLUMN IF NOT EXISTS instagram_url TEXT,
ADD COLUMN IF NOT EXISTS bio TEXT,
ADD COLUMN IF NOT EXISTS is_company BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS tax_id TEXT,
ADD COLUMN IF NOT EXISTS tax_country TEXT,
ADD COLUMN IF NOT EXISTS notify_on_sale BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS notify_on_payout BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS notify_on_message BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS onboarding_completed_at TIMESTAMPTZ;
