/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ContactCardPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  birthdayDayFormat: "numeric",
  birthdayMonthFormat: "short",
  birthdayYearFormat: "numeric",
  discordClient: true
};
function parseStringsToMap(strings) {
  const result = {};
  strings.forEach((str) => {
    const [keyPart, valuePart] = str.split(":");
    if (valuePart !== void 0) {
      const key = keyPart.trim().toLowerCase();
      let valueTrimmed = valuePart.trim();
      if (valueTrimmed.startsWith("[") && valueTrimmed.endsWith("]")) {
        valueTrimmed = valueTrimmed.slice(1, -1);
      }
      let value;
      if (key == "birthday") {
        value = [valueTrimmed];
      } else {
        value = valueTrimmed.split(",").map((item) => item.trim()).filter((item) => item.length > 0);
      }
      if (Array.isArray(result[key])) {
        result[key].push(...value);
      } else {
        result[key] = value;
      }
    }
  });
  return result;
}
function parseMapToContact(map) {
  var _a, _b, _c, _d, _e, _f, _g;
  const contact = {
    name: ((_a = map["name"]) != null ? _a : [])[0],
    nickname: ((_b = map["name"]) != null ? _b : []).slice(1),
    birthday: ((_c = map["birthday"]) != null ? _c : [])[0],
    phone: (_d = map["phone"]) != null ? _d : [],
    email: (_e = map["email"]) != null ? _e : [],
    insta: (_f = map["insta"]) != null ? _f : [],
    discord: ((_g = map["discord"]) != null ? _g : []).map(stringToDiscordHandleAndChannelId)
  };
  if (contact.phone) {
    contact.phone = contact.phone.map(formatPhoneNumber);
  }
  if (contact.email) {
    contact.email = contact.email.filter(validateEmail);
  }
  if (contact.insta) {
    contact.insta = contact.insta.map(removeLeadingAt);
  }
  return contact;
}
function stringToDiscordHandleAndChannelId(text) {
  const cleanedText = text.startsWith("<") && text.endsWith(">") ? text.slice(1, -1) : text;
  if (cleanedText.contains("|")) {
    const [handle, dm_channel_id] = cleanedText.split("|");
    if (isNaN(Number(dm_channel_id))) {
      return {
        handle
      };
    }
    return {
      handle,
      dm_channel_id
    };
  } else {
    return {
      handle: cleanedText
    };
  }
}
function formatPhoneNumber(phone) {
  let cleaned = phone.replace(/\D/g, "");
  if (!cleaned.startsWith("1") && cleaned.length === 10) {
    cleaned = "1" + cleaned;
  }
  return cleaned.replace(/^(\d{1})(\d{3})(\d{3})(\d{4})$/, "+$1 ($2) $3-$4");
}
var emailRegex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
function validateEmail(email) {
  return emailRegex.test(email);
}
function removeLeadingAt(input) {
  return input.startsWith("@") ? input.slice(1) : input;
}
var yearRegex = /\b(?:(?:19|20)[0-9]{2})|(?:3[3-9]|[4-9][0-9])\b/;
function formatBirthday(birthdayString, dayFormat, monthFormat, yearFormat) {
  const birthdate = new Date(birthdayString);
  if (isNaN(birthdate.getTime())) {
    return null;
  } else if (yearRegex.test(birthdayString)) {
    return Intl.DateTimeFormat("en-US", {
      day: dayFormat,
      month: monthFormat,
      year: yearFormat
    }).format(birthdate);
  } else {
    return Intl.DateTimeFormat("en-US", {
      day: dayFormat,
      month: monthFormat
    }).format(birthdate);
  }
}
function calculateAge(birthdayString) {
  const birthdate = new Date(birthdayString);
  if (isNaN(birthdate.getTime())) {
    return null;
  }
  if (!yearRegex.test(birthdayString)) {
    return null;
  }
  const today = new Date();
  let age = today.getFullYear() - birthdate.getFullYear();
  const monthDifference = today.getMonth() - birthdate.getMonth();
  const dayDifference = today.getDate() - birthdate.getDate();
  if (monthDifference < 0 || monthDifference === 0 && dayDifference < 0) {
    age--;
  }
  return age;
}
var ContactCardPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new ContactCardSettingTab(this.app, this));
    this.registerMarkdownCodeBlockProcessor("contact", (source, element, context) => {
      var _a;
      const rows = source.split("\n").map((row) => row.trim()).filter((row) => row.length > 0);
      const map = parseStringsToMap(rows);
      const contact = parseMapToContact(map);
      if (contact) {
        const contactCard = element.createDiv({ cls: "contact-card" });
        if (contact.name) {
          contactCard.createDiv({ cls: "contact-name", text: contact.name });
        }
        if (contact.nickname.length > 0) {
          contactCard.createDiv({ cls: "contact-field", text: `Nickname${contact.nickname.length > 1 ? "s" : ""}: ${contact.nickname.join(", ")}` });
        }
        if (contact.birthday) {
          const birthdayString = (_a = formatBirthday(
            contact.birthday,
            this.settings.birthdayDayFormat,
            this.settings.birthdayMonthFormat,
            this.settings.birthdayYearFormat
          )) != null ? _a : contact.birthday;
          const age = calculateAge(contact.birthday);
          const ageString = age ? ` (${age} years old)` : "";
          contactCard.createDiv({ cls: "contact-field", text: `Birthday: ${birthdayString}${ageString}` });
        }
        contact.phone.forEach((phone) => {
          const phoneDiv = contactCard.createDiv({ cls: "contact-field", text: "\u{1F4DE} " });
          phoneDiv.createEl("a", { href: "tel:" + phone, text: phone });
          const messageDiv = contactCard.createDiv({ cls: "contact-field", text: "\u{1F4AC} " });
          messageDiv.createEl("a", { href: "sms:" + phone, text: phone });
        });
        contact.email.forEach((email) => {
          const emailDiv = contactCard.createDiv({ cls: "contact-field", text: "\u{1F4E7} " });
          emailDiv.createEl("a", { href: "mailto:" + email, text: email });
        });
        contact.insta.forEach((insta) => {
          const instaDiv = contactCard.createDiv({ cls: "contact-field", text: "\u{1F4F7} " });
          instaDiv.createEl("a", { href: `https://www.instagram.com/${insta}/`, text: "@" + insta });
        });
        contact.discord.forEach((discord) => {
          if (discord.dm_channel_id) {
            const discordDiv = contactCard.createDiv({ cls: "contact-field", text: "\u{1F3AE} " });
            discordDiv.createEl("a", {
              href: (this.settings.discordClient ? "discord://" : "https://discord.com") + `/channels/@me/${discord.dm_channel_id}`,
              text: discord.handle
            });
          } else {
            contactCard.createDiv({ cls: "contact-field", text: "\u{1F3AE} " + discord.handle });
          }
        });
        if (contactCard.childElementCount <= 1) {
          contactCard.createDiv({ cls: "contact-field", text: "(no contact info)" });
        }
      }
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var ContactCardSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Birthday day format").setDesc("Display the day without or with a leading zero (when below 10)").addDropdown((dropdown) => dropdown.addOption("numeric", "3").addOption("2-digit", "03").setValue(this.plugin.settings.birthdayDayFormat).onChange(async (value) => {
      this.plugin.settings.birthdayDayFormat = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Birthday month format").setDesc("Display the entire month name, the three-letter abbreviation, only the first letter, the number representation, or number with a leading zero (when below 10)").addDropdown((dropdown) => dropdown.addOption("long", "March").addOption("short", "Mar").addOption("narrow", "M").addOption("numeric", "3").addOption("2-digit", "03").setValue(this.plugin.settings.birthdayMonthFormat).onChange(async (value) => {
      this.plugin.settings.birthdayMonthFormat = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Birthday year format").setDesc("Display the entire year or only the last two digits").addDropdown((dropdown) => dropdown.addOption("numeric", "1999").addOption("2-digit", "99").setValue(this.plugin.settings.birthdayYearFormat).onChange(async (value) => {
      this.plugin.settings.birthdayYearFormat = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Discord client installed").setDesc("Enable if you want to Discord links to open in your desktop/mobile client, disable if you want to open the Discord website").addToggle((toggle) => toggle.setValue(this.plugin.settings.discordClient).onChange(async (value) => {
      this.plugin.settings.discordClient = value;
      await this.plugin.saveSettings();
    }));
  }
};


/* nosourcemap */