# Blog-style shop bios (part 2 of 2). Imported by merge_blog_style_artist_bios.py
from __future__ import annotations

SHOP_BIOS_PART2: dict[str, dict[str, str]] = {
    "moshe-gilboa": {
        "heroHook": "Moshe Gilboa is an Israeli artist and designer whose practice doesn't file neatly. (moshegilboa)",
        "storyFullText": "Moshe Gilboa is an Israeli artist and designer whose practice doesn't file neatly. Animation, UI, indie games, and illustrated essays share the same humor \u2014 work that winks while it teaches.\n\nHe documents shipped projects in long-form on Medium, which tells you something about how seriously he takes the process of making. That sense of timing stays visible even in still images: the composition feels paused rather than frozen. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThe work does not need a heavy explanation to hold attention. It earns that attention through pace, pressure, color, and a clear sense of where the artist wants the eye to land.\n\nThere is enough clarity to enter the image quickly, and enough friction to keep looking once the subject has settled.",
        "activeSince": "LinkedIn cites ~10 years across UX/UI, game art, animation, illustration; Bezalel Academy studies referenced",
    },
    "my-sunbeam": {
        "heroHook": "Taylor works as My Sunbeam from London, making illustration that feels both nostalgic and freshly odd. (@mysunbeam)",
        "storyFullText": "Taylor works as My Sunbeam from London, making illustration that feels both nostalgic and freshly odd. The characters often look as if they have stepped out of sticker books, old packaging, and late-night radio jingles, but the humor is gentler and stranger than simple retro pastiche.\n\nTexture matters in this work. Distressed edges, playful lettering, and warm character design give the images the feeling of objects that have already lived a little, even when they are newly made.\n\nPublic material around My Sunbeam connects the practice to London's illustration and independent design scenes, with studio-linked projects documenting the work's playful character-led approach.\n\nThe charm is immediate, but the images are not lazy. They are carefully tuned little worlds: friendly at first glance, then full of small expressions, wonky details, and mood shifts that reward a slower look.",
        "activeSince": "",
    },
    "nasca-uno": {
        "heroHook": "NASCA Uno is a Berlin-based artist whose walls carry the patience of drawing and the charge of graffiti. (@nasca_one)",
        "storyFullText": "NASCA Uno is a Berlin-based artist whose walls carry the patience of drawing and the charge of graffiti. His murals often bring together myth, anatomy, urban memory, and figures that seem to come from a century you cannot quite place.\n\nThe work has a dense narrative quality. A single piece can feel like a chapter from a larger story, full of symbols and bodies that are not explained so much as encountered.\n\nPublic research connects the practice to Berlin mural activity, festival walls, and museum-context work, including a STRAAT Museum collection entry that has been referenced in prior documentation.\n\nWhat makes NASCA Uno compelling is the tension between control and atmosphere. The drawing is careful, but the finished image still feels unstable in the best way, as if the wall is remembering something.",
        "activeSince": "Early 1990s birth near Munich; graffiti-to-mural path per artsmania.ca (2020)",
    },
    "nia-shtai": {
        "heroHook": "Nia Shtai is a Tel Aviv illustrator and graphic designer working across Procreate and screen-based tools. (nia.shtai.art)",
        "storyFullText": "Nia Shtai is a Tel Aviv illustrator and graphic designer working across Procreate and screen-based tools. Characters, fashion, and a certain dream logic share the same saturated color space.\n\nShe also runs an upcycled fashion brand, which makes sense \u2014 the same care about image and material runs through both. Tel Aviv enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nAcross formats, the work is most alive when it lets polish and personality sit together: clean enough to read fast, human enough to keep its edges.\n\nThere is enough clarity to enter the image quickly, and enough friction to keep looking once the subject has settled.",
        "activeSince": "Upcycled fashion brand narrative cites designing since 2011 (Dressed by Danielle blog interview, 2023)",
    },
    "nurit-gross": {
        "heroHook": "Nurit Gross is a Tel Aviv illustrator and designer who graduated from Bezalel in 2019 and works across cut paper, gouache, markers, and digital paint. (nurit_gross)",
        "storyFullText": "Nurit Gross is a Tel Aviv illustrator and designer who graduated from Bezalel in 2019 and works across cut paper, gouache, markers, and digital paint. Her images often feel handmade even when the finish is clean, with folk pattern, humor, and small visual surprises carrying the mood.\n\nChildren's books, magazine work, museum projects, and municipal commissions all seem to feed the same curiosity: how to make an image feel generous without making it simple. Gross is good at letting playfulness and precision share the same surface.\n\nPublic biography material notes the Israel Museum's Ben-Yitzhak Award in 2022 and inclusion in Society of Illustrators annuals. Her own site continues to frame the practice around illustration, design, sketches, and process.\n\nThe work is interesting because it does not separate craft from wit. A cut shape, a tiny expression, or a patterned field can do the emotional work of a whole paragraph.",
        "activeSince": "B.Des. Bezalel Academy of Art and Design, class of 2019 (nuritgross.com/about)",
    },
    "odsk": {
        "heroHook": "Anthony Daudet works as ODSK from Nantes, where tattooing and illustration inform each other. (@odsk_)",
        "storyFullText": "Anthony Daudet works as ODSK from Nantes, where tattooing and illustration inform each other. Nantes enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land.\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary. That mix of accessibility and discipline is what keeps the practice from feeling decorative. The surface is inviting, but the choices underneath are specific.\n\nThere is enough clarity to enter the image quickly, and enough friction to keep looking once the subject has settled.\n\nAcross formats, the practice is less about repeating a signature trick than about returning to a set of visual instincts and testing what they can carry next.",
        "activeSince": "",
    },
    "ollie-smither": {
        "heroHook": "Ollie Smither is a UK illustrator based in Devon who works in fine line. (@os.illustration)",
        "storyFullText": "Ollie Smither is a UK illustrator based in Devon who works in fine line. Forests, figures, and small impossible details accumulate in drawings you discover gradually.\n\nThe mood is contemplative and slightly uncanny \u2014 work for people who like to lean in. Devon enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land. In 2026, the practice stayed active through Monograph Wanderlust Ink (Epic Ink / Quarto Group; US Apr 21 / UK May 7 per publisher).\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.",
        "activeSince": "",
    },
    "or-bar-el": {
        "heroHook": "Or Bar-El's SketchBoom project puts a camera on the drawing hand and broadcasts the act of making live. (@or_bar_el)",
        "storyFullText": "Or Bar-El's SketchBoom project puts a camera on the drawing hand and broadcasts the act of making live. Bezalel animation training and a decorated student film set the foundation; independent practice pulled him back toward illustration and walls.\n\nThe common thread is immediacy \u2014 drawing as an event you witness, not just an object you receive. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThat mix of accessibility and discipline is what keeps the practice from feeling decorative. The surface is inviting, but the choices underneath are specific.",
        "activeSince": "",
    },
    "ori-toor": {
        "heroHook": "Ori Toor improvises. His drawings accumulate line by line, each one suggesting the next, until the surface is full of creatures, patterns, and color that refuses to stay put. (@oritoor)",
        "storyFullText": "Ori Toor improvises. His drawings accumulate line by line, each one suggesting the next, until the surface is full of creatures, patterns, and color that refuses to stay put.\n\nHe studied at Shenkar, worked newspaper layout for a while, and ended up making commercial work for Nike, Wired, and Cartoon Network alongside a personal practice built around what he calls \"Gibberish\" drawings \u2014 improvisational, meditative, the opposite of planned. His work appeared on Adobe Illustrator's splash screen in 2018. People describe it like music you can see.\n\nTel Aviv enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land.\n\nThe work does not need a heavy explanation to hold attention. It earns that attention through pace, pressure, color, and a clear sense of where the artist wants the eye to land.",
        "activeSince": "Shenkar graduate 2010 (Pictoplasma conference bio)",
    },
    "paola-delfin": {
        "heroHook": "Paola Delf\u00edn is a Mexican muralist whose large-scale women seem to grow from the wall itself. (@paola_delfin)",
        "storyFullText": "Paola Delf\u00edn is a Mexican muralist whose large-scale women seem to grow from the wall itself. Black, white, and soft gray carry the emotion without raising their voice \u2014 curves that echo Art Nouveau and street timing in the same breath.\n\nHer figures have appeared in cities across the Americas and Europe, and each one feels like it belongs to the neighborhood it lives in. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nWhat gives the practice its pull is the balance between immediate charm and careful construction; the image opens quickly, then keeps revealing how it was built.",
        "activeSince": "Born 1989 (Wikipedia / cultura.gob.mx semblanza)",
    },
    "phil-huelz": {
        "heroHook": "Phil Huelz works from Cologne with a visual language built around bold color, expressive faces, and approachable ideas. (@phil.huelz)",
        "storyFullText": "Phil Huelz works from Cologne with a visual language built around bold color, expressive faces, and approachable ideas. His illustration has the feel of a conversation: direct, warm, and willing to talk about real emotion without making the image heavy.\n\nThe work moves between editorial, advertising, personal pieces, and object-led projects. A character may look playful at first, but the expression usually carries something more complicated underneath.\n\nRecent public research points to 2025 attention around Tanglehug and mentions of Culture Arts Expo in Visalia, with further Cologne activity noted for 2026. Those details should stay flexible, but they show an active practice moving between image and object.\n\nWhat makes Huelz stand out is the balance between accessibility and feeling. The drawing is friendly enough to invite you in, then specific enough to keep the emotion from turning generic.",
        "activeSince": "",
    },
    "psoman": {
        "heroHook": "Psoman studied graphic design in Belgium and welding and polyester fabrication in Switzerland before committing to painting full time. (@psoman_ptk)",
        "storyFullText": "Psoman studied graphic design in Belgium and welding and polyester fabrication in Switzerland before committing to painting full time. Hybrid animals and surreal bodies carry quiet warnings about nature under pressure across walls in Europe and Asia.\n\nA school residency in Taiwan in 2024 proved the characters travel without losing anything. The STRAAT Museum in Amsterdam holds one of his pieces. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit.\n\nIn 2026, the practice stayed active through Group: Entre Art urbain et Art contemporain (with Noir Artist, Jaune), Ch\u00e2teau de Waroux, Ans/Li\u00e8ge, Belgium \u2014 3 Apr\u201317 May 2026. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.",
        "activeSince": "",
    },
    "raki": {
        "heroHook": "RAF Page works as RAKI, an illustrator from the Philippines whose large images feel like storybook scenes built for public scale. (@raki.official.art)",
        "storyFullText": "RAF Page works as RAKI, an illustrator from the Philippines whose large images feel like storybook scenes built for public scale. Warm color, rounded characters, and mythic touches make the work accessible without sanding away its strangeness.\n\nRAKI's visual world often carries the emotional clarity of children's illustration while speaking to adult ideas about imagination, quiet strength, and selfhood. The result is generous, direct, and easy to enter.\n\nRecent public material connects the practice to Bangkok Illustration Fair activity, with the 2025 artist program still visible in 2026 research. That Southeast Asian illustration context helps place the work beyond a single local scene.\n\nWhat makes RAKI engaging is the sincerity. The images do not hide behind irony; they invite the viewer into a softer kind of power and trust the drawing to carry it.",
        "activeSince": "",
    },
    "refiloe-mnisi": {
        "heroHook": "Refiloe Mnisi is a Johannesburg illustrator whose figures arrive dressed with intention. (@urfavsweatpants)",
        "storyFullText": "Refiloe Mnisi is a Johannesburg illustrator whose figures arrive dressed with intention. The work sits at the intersection of streetwear culture and portrait confidence \u2014 each character feels assembled on purpose, with attitude to match.\n\nThe voice is sharp and unapologetically stylish. The point is not to make Refiloe Mnisi easy to categorize; the work is more interesting because it keeps moving between image, object, and atmosphere. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nWhat gives the practice its pull is the balance between immediate charm and careful construction; the image opens quickly, then keeps revealing how it was built.\n\nThere is enough clarity to enter the image quickly, and enough friction to keep looking once the subject has settled.",
        "activeSince": "",
    },
    "rik-lee": {
        "heroHook": "Rik Lee is a Melbourne illustrator who mixes tattoo flash, fashion editorial, and diary drawing into something that holds together. (@rikleeillustration)",
        "storyFullText": "Rik Lee is a Melbourne illustrator who mixes tattoo flash, fashion editorial, and diary drawing into something that holds together. Women, wolves, and wry slogans repeat like favorite records \u2014 familiar in structure, specific in feeling.\n\nRetro in palette without being in costume. Melbourne enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nWhat gives the practice its pull is the balance between immediate charm and careful construction; the image opens quickly, then keeps revealing how it was built.\n\nThere is enough clarity to enter the image quickly, and enough friction to keep looking once the subject has settled.",
        "activeSince": "",
    },
    "s-a-r-g-o-n": {
        "heroHook": "S A R G O N is best understood, for now, through the public @oky.sargon feed: a compact visual diary of illustration, motion, and experiments released close to the moment of\u2026",
        "storyFullText": "S A R G O N is best understood, for now, through the public @oky.sargon feed: a compact visual diary of illustration, motion, and experiments released close to the moment of making.\n\nBecause there is no reliable public biography tying the handle to a fuller artist history, the bio stays deliberately narrow. The visible work is graphic, quick-moving, and exploratory, with the social feed functioning as the main record of the practice.\n\nThat thinness is also useful: it keeps the focus on what can be seen rather than on borrowed identity claims. The interest is in the pace of the images and the sense of a style still being tested in public.",
        "activeSince": "",
    },
    "samme-snow": {
        "heroHook": "Samme Snow finished a Graphic Communication degree in Farnham in 2013 and chose walls over office work. (@snowhandsworld)",
        "storyFullText": "Samme Snow finished a Graphic Communication degree in Farnham in 2013 and chose walls over office work. He has painted corporate lobbies, skate spaces, and magazine editorial spreads with the same generous, unhurried line.\n\nSince 2020 he has run open coloring workshops with thousands of participants, which feels continuous with the mural practice rather than separate from it. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. In 2025, the practice stayed active through Workshop residency, Secret 7\" Colouring Experience, NOW Gallery, Greenwich Peninsula, London, UK.\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nWhat gives the practice its pull is the balance between immediate charm and careful construction; the image opens quickly, then keeps revealing how it was built.",
        "activeSince": "Graphic Communication degree Farnham, 2013 (sammesnow.com/about)",
    },
    "sancho": {
        "heroHook": "Sancho Sancho is a visual artist and illustrator who grew up in Birmingham and Shanghai before settling in Amsterdam. (@bysancho)",
        "storyFullText": "Sancho Sancho is a visual artist and illustrator who grew up in Birmingham and Shanghai before settling in Amsterdam. Humor runs just underneath everything.\n\nAmsterdam enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary. What gives the practice its pull is the balance between immediate charm and careful construction; the image opens quickly, then keeps revealing how it was built.\n\nThere is enough clarity to enter the image quickly, and enough friction to keep looking once the subject has settled.\n\nAcross formats, the practice is less about repeating a signature trick than about returning to a set of visual instincts and testing what they can carry next.",
        "activeSince": "",
    },
    "saturn-png": {
        "heroHook": "Hermann works as saturn_png, pairing hard-edge abstraction with something that echoes ancient ceramic and Greek pottery. (@saturn_png)",
        "storyFullText": "Hermann works as saturn_png, pairing hard-edge abstraction with something that echoes ancient ceramic and Greek pottery. Procreate grain and analog discipline come together in illustrations that feel carved as much as drawn.\n\nThe work asks how digital art can feel archaeological. France enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nAcross formats, the work is most alive when it lets polish and personality sit together: clean enough to read fast, human enough to keep its edges.\n\nThere is enough clarity to enter the image quickly, and enough friction to keep looking once the subject has settled.",
        "activeSince": "",
    },
    "studio-giftig": {
        "heroHook": "Studio Giftig is Niels van Swaemen and Kaspar van Leek, two Dutch painters who have been working together since 2007 and painting murals full time since 2012. (studiogiftig)",
        "storyFullText": "Studio Giftig is Niels van Swaemen and Kaspar van Leek, two Dutch painters who have been working together since 2007 and painting murals full time since 2012. The work is surreal realism at building scale \u2014 cinematic light, careful staging, finished surfaces that make you wonder how human hands did it.\n\nThey photograph their own reference material, which keeps everything under their control and recognizably theirs. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThat mix of accessibility and discipline is what keeps the practice from feeling decorative. The surface is inviting, but the choices underneath are specific.",
        "activeSince": "Collaborating since 2007; dedicated to murals full-time from 2012 (studiogiftig.nl/about)",
    },
    "taloosh": {
        "heroHook": "Taloosh Studio works from Haifa across illustration, promo art, branding, and moving-image culture. (@taloosh.studio)",
        "storyFullText": "Taloosh Studio works from Haifa across illustration, promo art, branding, and moving-image culture. The studio's work has the pace of music and nightlife: fast, graphic, bright, and built to make a project feel like it already has a world around it.\n\nInstead of treating campaigns as flat assets, Taloosh tends to build atmosphere. Posters, short films, exhibition material, and cultural visuals share a taste for bold character, saturated rhythm, and a direct line to local creative scenes.\n\nAvailable public material points to ongoing cultural and exhibition-related work, including material connected to Beit Hankin Gallery programming. The clearest read is also the safest one: this is a studio practice rooted in visual energy, not a single fixed medium.\n\nWhat makes Taloosh worth watching is the way the work feels designed for movement even when it is still. It carries Haifa's coastal confidence without turning that location into a slogan.",
        "activeSince": "",
    },
    "tania-yakunova": {
        "heroHook": "Tania Yakunova was born and raised in Kyiv, worked in the creative industry for years, and became a full-time illustrator in 2014. (@anni_tett)",
        "storyFullText": "Tania Yakunova was born and raised in Kyiv, worked in the creative industry for years, and became a full-time illustrator in 2014. She relocated to London in 2023.\n\nThe work crosses commercial illustration and fine art \u2014 geometry, texture, and literary reference sharing the same table. Her best work, she says, comes from merging different realms, which the practice clearly does. London enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land.\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThat mix of accessibility and discipline is what keeps the practice from feeling decorative. The surface is inviting, but the choices underneath are specific.",
        "activeSince": "Full-time illustrator from 2014; relocated to UK 2023 per yakunova.com/about",
    },
    "thales-towers": {
        "heroHook": "Thales Towers says on his own site that he doesn't know how to paint faces, so he paints towers on them instead. (thalestowers)",
        "storyFullText": "Thales Towers says on his own site that he doesn't know how to paint faces, so he paints towers on them instead. Animated GIFs spread the same cast worldwide on GIPHY.\n\nThe humor is consistent and the drawing backs it up. Tel Aviv enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThe work does not need a heavy explanation to hold attention. It earns that attention through pace, pressure, color, and a clear sense of where the artist wants the eye to land.\n\nThere is enough clarity to enter the image quickly, and enough friction to keep looking once the subject has settled.",
        "activeSince": "Not dated on the official one-page bio consulted",
    },
    "thibaud-herem": {
        "heroHook": "Thibaud H\u00e9rem is a French illustrator known for hand-drawn architectural work in pencil and Indian ink. (@thibaudherem)",
        "storyFullText": "Thibaud H\u00e9rem is a French illustrator known for hand-drawn architectural work in pencil and Indian ink. The buildings feel walked, not photographed \u2014 facades rendered with an obsessive patience that turns a structure into a portrait.\n\nHe has worked for Herm\u00e8s, Netflix (Our Beloved Summer), and Four Seasons, published books with Nobrow and Laurence King, and held a solo show in Seoul. France / United Kingdom enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nWhat gives the practice its pull is the balance between immediate charm and careful construction; the image opens quickly, then keeps revealing how it was built.",
        "activeSince": "",
    },
    "thomas-stary": {
        "heroHook": "Tom\u00e1\u0161 Star\u00fd is a Prague designer who trained in industrial design at the University of West Bohemia and has been painting murals since 2010. (@tomasstary.studio)",
        "storyFullText": "Tom\u00e1\u0161 Star\u00fd is a Prague designer who trained in industrial design at the University of West Bohemia and has been painting murals since 2010. His walls treat the city like a typographic poster \u2014 geometry, rhythm, and the kind of balance that industrial design training quietly enforces.\n\nThe same logic runs through illustration work and architectural-scale pieces alike. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThe best way into the work is through its decisions: what gets simplified, what stays strange, and where the image leaves room for the viewer to finish the thought.",
        "activeSince": "Murals since 2010 (tomasstary.com); MA industrial design UWB Pilsen 2017\u20132020 (LinkedIn)",
    },
    "tiago-hesp": {
        "heroHook": "Tiago Hesp was born in 1981, trained in scenography at Escola Superior de Teatro e Cinema in Lisbon, and has been doing graffiti since 1998. (tiagohesp)",
        "storyFullText": "Tiago Hesp was born in 1981, trained in scenography at Escola Superior de Teatro e Cinema in Lisbon, and has been doing graffiti since 1998. His practice now spans mural painting, music, illustration, and theatre design \u2014 disciplines that share a grammar of stage and surface.\n\nHe describes painting as starting from an aggressive black line and chasing balance between shadow and color. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nAcross formats, the work is most alive when it lets polish and personality sit together: clean enough to read fast, human enough to keep its edges.",
        "activeSince": "Graffiti since 1998; born 1981; scenography degree from Escola Superior de Teatro e Cinema de Lisboa (tiagohesp.com/profile)",
    },
    "tiffany-chin": {
        "heroHook": "Tiffany Chin studied illustration at OCAD University in Toronto and graduated in 2022 with a medal and a stack of award wins \u2014 Society of Illustrators, Applied Arts\u2026 (twkchin)",
        "storyFullText": "Tiffany Chin studied illustration at OCAD University in Toronto and graduated in 2022 with a medal and a stack of award wins \u2014 Society of Illustrators, Applied Arts, Communication Arts, Creative Quarterly. The work is inspired by 1960s and 70s poster culture and carries that era's typographic confidence into contemporary illustration.\n\nShe has been shortlisted or recognized every year since graduation. The work understands graphic impact: shape, type, and color arrive quickly, then leave enough tension to keep looking. Society of Illustrators NYC annuals (2022\u20132025), Northern Contemporary Toronto 2023, Haight Street Art Center 2024, OCAD GradEx 2022, etc.\n\n(twkchin.com/about). The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nWhat gives the practice its pull is the balance between immediate charm and careful construction; the image opens quickly, then keeps revealing how it was built.",
        "activeSince": "OCAD U BDes Illustration 2018\u20132022; freelance illustrator from 2022 per LinkedIn/twkchin.com",
    },
    "troy-browne": {
        "heroHook": "Troy Browne is a Nottingham-based artist and motion designer who went independent in 2018 after years in studio environments. (@troybrowne)",
        "storyFullText": "Troy Browne is a Nottingham-based artist and motion designer who went independent in 2018 after years in studio environments. That background gives the work a strong sense of timing: collage, hand-drawn movement, digital finishing, and composition all seem to understand the frame before and after the one you see.\n\nHis images often feel assembled in motion, even when they are still. Shape, texture, and character sit together with the energy of animation paused at the most interesting moment.\n\nRecent public material points to his 2025 appearance in Confetti Industry Week programming across Nottingham and London, while earlier public material documents representation by The Different Folk and a client-facing motion practice.\n\nThe work is compelling because it keeps the object and the timeline in conversation. You can read it as an image, but you can also feel the sequence that might have produced it.",
        "activeSince": "Freelance motion/illustration from Dec 2018 (LinkedIn); NTU Multimedia BSc 2007\u20132010",
    },
    "troy-browne-1": {
        "heroHook": "Troy Browne is a Nottingham-based artist and motion designer who went independent in 2018 after years in studio environments. (@troybrowne)",
        "storyFullText": "Troy Browne is a Nottingham-based artist and motion designer who went independent in 2018 after years in studio environments. That background gives the work a strong sense of timing: collage, hand-drawn movement, digital finishing, and composition all seem to understand the frame before and after the one you see.\n\nHis images often feel assembled in motion, even when they are still. Shape, texture, and character sit together with the energy of animation paused at the most interesting moment.\n\nRecent public material points to his 2025 appearance in Confetti Industry Week programming across Nottingham and London, while earlier public material documents representation by The Different Folk and a client-facing motion practice.\n\nThe work is compelling because it keeps the object and the timeline in conversation. You can read it as an image, but you can also feel the sequence that might have produced it.",
        "activeSince": "Freelance motion/illustration from Dec 2018 (LinkedIn); NTU Multimedia BSc 2007\u20132010",
    },
    "twoone-hiroyasu-tsuri": {
        "heroHook": "Hiroyasu Tsuri left Yokohama for Melbourne in 2003 and spent years absorbing street and graffiti culture before formalizing his practice. (t_w_o_o_n_e)",
        "storyFullText": "Hiroyasu Tsuri left Yokohama for Melbourne in 2003 and spent years absorbing street and graffiti culture before formalizing his practice. He coined the term \"Raw Mark Making\" to describe a style that runs classical drawing through street velocity.\n\nRepresented by Backwoods Gallery in Melbourne, he has shown in institutions in Canberra, Amsterdam, and Munich, and his work is in museum collections. Graffiti grammar holding museum weight. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit.\n\nSolo: Backwoods Gallery sequences (e.g., RAW MARK MAKING 2020, THE BLUE PERIOD 2023, PHYSICAL ACTION AS THINKING FORM 2025), European gallery stops, Japanese embassy show Brussels 2019, etc. Groups: Space Invaders NGA 2010, Straat museum opening 2020, MUCA portrait survey 2018 (hiroyasutsuri.com/about CV). The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.",
        "activeSince": "Born 1985 Yokohama; moved to Melbourne 2003; diploma Swinburne 2009; Berlin hub from 2014; Backwoods Gallery representation since 2010",
    },
    "tyler-shelton": {
        "heroHook": "Tyler Shelton started painting portraits of rock stars at 20 and turned his Instagram into a business before he was 30. (sheltonartco)",
        "storyFullText": "Tyler Shelton started painting portraits of rock stars at 20 and turned his Instagram into a business before he was 30. The practice moved from music iconography toward a broader pop culture range \u2014 thick acrylic, stencil confidence, celebrity portraits that treat fame as a material like any other.\n\nBright, cheeky, and backed by real craft. Texas enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land. In 2024, the practice stayed active through Tyler Shelton collection (retail stockist context), Austin Art Garage, Austin, Texas.\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThe best way into the work is through its decisions: what gets simplified, what stays strange, and where the image leaves room for the viewer to finish the thought.",
        "activeSince": "Turned Instagram @sheltonartco into a business at age 20; article context at age 29 (Dallas Observer)",
    },
    "unapaulogetic": {
        "heroHook": "Paul Rozenboim publishes as Unapaulogetic \u2014 a Tel Aviv multidisciplinary practice fluent in motion, typography, illustration, and installation. (unapaulogetic_)",
        "storyFullText": "Paul Rozenboim publishes as Unapaulogetic \u2014 a Tel Aviv multidisciplinary practice fluent in motion, typography, illustration, and installation. Projects chase physics through software: pendulums, generative systems, typographic objects frozen mid-spin.\n\nThat sense of timing stays visible even in still images: the composition feels paused rather than frozen. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary. That mix of accessibility and discipline is what keeps the practice from feeling decorative.\n\nThe surface is inviting, but the choices underneath are specific.\n\nThat mix of accessibility and discipline is what keeps the practice from feeling decorative. The surface is inviting, but the choices underneath are specific.\n\nThere is enough clarity to enter the image quickly, and enough friction to keep looking once the subject has settled.",
        "activeSince": "Public bios cite 10+ years in design/visual work (The Street Lamp artist blurb)",
    },
    "vivaladybug": {
        "heroHook": "Viva La Ladybug is an illustrator whose public work moves through bold characters, stickers, GIFs, and social-image culture. (@vivalaladybug)",
        "storyFullText": "Viva La Ladybug is an illustrator whose public work moves through bold characters, stickers, GIFs, and social-image culture. The energy is bright and immediate: mascot-like figures, thick outlines, and expressions built to move even when the image is still.\n\nThe practice is especially legible online, where loops and small reactions become part of how people talk to each other. That does not make the work throwaway; it makes timing, clarity, and personality unusually important.\n\nThe available public trail is thinner than for many artists here, with GIPHY and Instagram carrying most of the visible record. The channel material links the work to Aviva Charles and the @vivalaladybug identity.\n\nWhat makes the work useful and charming is its emotional directness. These are images made to travel quickly, but the best ones keep a handmade pulse inside the speed.",
        "activeSince": "",
    },
    "woizo": {
        "heroHook": "Woizo is a painter and muralist based in Toulouse who fills walls with narrative \u2014 creatures standing in for human impulses, better and worse. (@woizoner)",
        "storyFullText": "Woizo is a painter and muralist based in Toulouse who fills walls with narrative \u2014 creatures standing in for human impulses, better and worse. Graphic clarity keeps the story readable from across the street; detail rewards getting closer.\n\nHumor, unease, and genuine beauty in the same frame. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. In 2024, the practice stayed active through Large-format mural (approx.\n\n7\u00d73 m), Coll\u00e8ge Fou Fou Fou, Saint-Georges-de-Reintembault, France. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThat mix of accessibility and discipline is what keeps the practice from feeling decorative. The surface is inviting, but the choices underneath are specific.",
        "activeSince": "",
    },
    "wotto": {
        "heroHook": "Craig Watkins is Wotto \u2014 a British illustrator based in Orange County who has been freelancing since graduating with a BA in Illustration and Design in 2000. (@wotto76)",
        "storyFullText": "Craig Watkins is Wotto \u2014 a British illustrator based in Orange County who has been freelancing since graduating with a BA in Illustration and Design in 2000. The practice has covered toys, apparel, advertising, and personal character universes in the years since.\n\nUK wit, California color, pop surrealism for people who read the label. Orange County enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land. In 2025, the practice stayed active through Adobe MAX Conference, Los Angeles, CA, USA.\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThat mix of accessibility and discipline is what keeps the practice from feeling decorative. The surface is inviting, but the choices underneath are specific.",
        "activeSince": "Freelance illustration since 2000 (wottoart.com About)",
    },
    "wuper-kec": {
        "heroHook": "Wuper Kec is a Serbian muralist who has been doing graffiti since 2006 and large-scale brush work for over five years. (@wuper_kec)",
        "storyFullText": "Wuper Kec is a Serbian muralist who has been doing graffiti since 2006 and large-scale brush work for over five years. Wolves, birds, and human hybrids hold walls across Europe.\n\nFairy tale on first look, something stranger on the second. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. In 2024, the practice stayed active through 9th Boulogne-sur-Mer Street Art Festival (festival mural program, July\u2013August).\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThe best way into the work is through its decisions: what gets simplified, what stays strange, and where the image leaves room for the viewer to finish the thought.",
        "activeSince": "Graffiti since 2006; brush murals for ~5+ years per Boulogne-sur-Mer blog (2024)",
    },
    "yippie-hey": {
        "heroHook": "YIPPIEHEY is a Hamburg illustration and animation studio founded by Jacob Eisinger. (@yippiehey)",
        "storyFullText": "YIPPIEHEY is a Hamburg illustration and animation studio founded by Jacob Eisinger. The client list is wide \u2014 Adidas, Samsung, McDonald's, Adobe, Deutsche Bahn, UNICEF \u2014 and so are the editorial credits: Wired, The New York Times, Der Spiegel.\n\nFriendly character design without being saccharine. That sense of timing stays visible even in still images: the composition feels paused rather than frozen. In 2025, the practice stayed active through Solo: Sammelsurium, Kultur & Gut / Kugu, Hamburg, Germany.\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThe work does not need a heavy explanation to hold attention. It earns that attention through pace, pressure, color, and a clear sense of where the artist wants the eye to land.",
        "activeSince": "10+ years career noted on yippiehey.com/about",
    },
    "yoaz": {
        "heroHook": "Yoaz is a Paris illustrator whose compositions feel like crowded rooms where every element is competing for attention and somehow harmony wins. (iamyoaz)",
        "storyFullText": "Yoaz is a Paris illustrator whose compositions feel like crowded rooms where every element is competing for attention and somehow harmony wins. Street art appetite and advertising discipline share the same restless DNA across murals, merch, and brand campaigns.\n\nHi-Fructose covered the work in 2019 and called it abuzz with activity \u2014 accurate for a practice built on controlled visual noise. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nWhat gives the practice its pull is the balance between immediate charm and careful construction; the image opens quickly, then keeps revealing how it was built.",
        "activeSince": "Documented editorial coverage in Hi-Fructose (March 2019) with prior client work trajectory",
    },
    "yonil": {
        "heroHook": "Jonathan Lax has been working as YONIL from Tel Aviv long enough to land in illustration annuals like IdN and Illustration Now!. (@yonil)",
        "storyFullText": "Jonathan Lax has been working as YONIL from Tel Aviv long enough to land in illustration annuals like IdN and Illustration Now!. The work comes from gig-poster culture \u2014 typographically bold, music-adjacent, loud enough to read from the back of a room.\n\nCommercial work and personal pieces share the same slightly anxious humor. Graphic, but never cold. The work understands graphic impact: shape, type, and color arrive quickly, then leave enough tension to keep looking.\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThe best way into the work is through its decisions: what gets simplified, what stays strange, and where the image leaves room for the viewer to finish the thought.",
        "activeSince": "",
    },
}
