# Blog-style shop bios (part 1 of 2). Imported by merge_blog_style_artist_bios.py
from __future__ import annotations

SHOP_BIOS_PART1: dict[str, dict[str, str]] = {
    "agus-rucula": {
        "heroHook": "Agus Rucula paints the human figure at mural scale and treats it as a meeting point \u2014 between community and artist, between dance and paint, between the people who made the\u2026 (@agus.rucula)",
        "storyFullText": "Agus Rucula paints the human figure at mural scale and treats it as a meeting point \u2014 between community and artist, between dance and paint, between the people who made the wall and the people walking past it. Her practice draws as much from photography and choreography as from urban art tradition.\n\nCommunities often participate directly. The result is empathy at the size of architecture. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit.\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nAcross formats, the work is most alive when it lets polish and personality sit together: clean enough to read fast, human enough to keep its edges.",
        "activeSince": "Murals since 2012 (Murales Buenos Aires interview, 2018)",
    },
    "ajax-blyth-piper": {
        "heroHook": "Ajax Blyth Piper graduated from University of the Arts London and has been working as a muralist on England's south coast since 2018. (@ajaxpiper)",
        "storyFullText": "Ajax Blyth Piper graduated from University of the Arts London and has been working as a muralist on England's south coast since 2018. His pieces read like narrative snapshots \u2014 figures you might know, palettes tuned to the neighborhood they live in.\n\nHe also designs typefaces, and the same attention to letterform runs through the mural work. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nWhat gives the practice its pull is the balance between immediate charm and careful construction; the image opens quickly, then keeps revealing how it was built.",
        "activeSince": "Murals since 2018 (Street Art Cities); b. 1997 per same listing",
    },
    "alice-bureau": {
        "heroHook": "Alice Hoffmann works as Bureau Alice from Zurich, after years spent inside international creative teams. (@bureau_alice)",
        "storyFullText": "Alice Hoffmann works as Bureau Alice from Zurich, after years spent inside international creative teams. That background shows in the way her illustrations can behave like brand systems without losing their hand-made warmth: clean line, exact color, and a knack for making a small gesture carry a whole mood.\n\nHer visual language often sits between editorial image-making, packaging, and art direction. The work can be minimal, but it is not cold; a figure, a plant, a room, or a small object becomes memorable because the drawing strips away noise instead of personality.\n\nRecent public material around Bureau Alice keeps the focus on illustration, art direction, and commercial image work for cultural and global clients, with Zurich as the working base. The strongest pieces feel quietly confident, as if every curve has already survived several rounds of editing.\n\nWhat makes the practice interesting is that it does not chase spectacle. It trusts proportion, wit, and restraint, then lets the viewer notice how much feeling can sit inside a very economical line.",
        "activeSince": "",
    },
    "alin-mor": {
        "heroHook": "Alin Mor graduated Bezalel in visual communications and built a practice around femininity, archetype, and spiritual symbolism at mural scale. (@alinmor)",
        "storyFullText": "Alin Mor graduated Bezalel in visual communications and built a practice around femininity, archetype, and spiritual symbolism at mural scale. The work asks, without quite saying it, who gets to occupy public space.\n\nIt answers with saturated, symbolic figures that are hard to walk past without stopping. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nAcross formats, the work is most alive when it lets polish and personality sit together: clean enough to read fast, human enough to keep its edges.\n\nThere is enough clarity to enter the image quickly, and enough friction to keep looking once the subject has settled.",
        "activeSince": "Freelance illustrator/graphic designer since 2016 (LinkedIn); Bezalel B.Des 2014\u20132017",
    },
    "animalitoland": {
        "heroHook": "Graciela Goncalves Da Silva works as Animalitoland, a practice that turns characters, murals, and emotional fictions into bright architectural worlds. (@animalitoland)",
        "storyFullText": "Graciela Goncalves Da Silva works as Animalitoland, a practice that turns characters, murals, and emotional fictions into bright architectural worlds. Born in Argentina and trained in design at the University of Buenos Aires, she has lived and worked across Buenos Aires, Madrid, Vancouver, and Los Angeles.\n\nHer murals and paintings often feel like graphic novels pressed into public space: precise figures, vivid acrylic color, and strange creatures carrying very human feelings. The style is playful, but the themes often circle belonging, displacement, and the search for an inner home.\n\nRecent activity in the research includes 2024 Hawaii Walls and 2025 projects in Los Angeles and Glendale, including Perseverance: 20 Years of Thinkspace and Art Share LA Summer Block Party.\n\nThe work travels well because it is not only decorative fantasy. It uses fantasy as a way to make emotion visible, turning walls into places where vulnerability can be loud, colorful, and still tender.",
        "activeSince": "Digital illustration from 1999; street painting from 2011; full-time nomadic from 2014 per animalitoland.com bio",
    },
    "antonia-lev": {
        "heroHook": "Antonia Lev is a Paris-based illustrator and street artist whose practice moves between wall painting, editorial imagery, and digital work. (@antonialev)",
        "storyFullText": "Antonia Lev is a Paris-based illustrator and street artist whose practice moves between wall painting, editorial imagery, and digital work. Her images are graphic and narrative, with figures and scenes that hold up at mural scale while still giving the eye something to follow close up.\n\nThe work has a storybook pulse, but it is not soft in a decorative way. Lines stay confident, characters carry attitude, and the compositions often feel like fragments of a larger scene caught mid-movement.\n\nRecent public material points to a 2025 mural project, The Dance of Blooming, connected to Mural City activity in the Paris region. Older public material also shows her moving between festival walls and illustration platforms, which fits the range of the practice.\n\nWhat makes Lev's work engaging is the way it treats public space as a narrative surface. A wall is not just scale; it is a place where a character, a gesture, or a small fiction can suddenly belong to the street.",
        "activeSince": "Behance lists professional start 4 Nov 2011 (verify on live profile)",
    },
    "antonia-lev-1": {
        "heroHook": "Antonia Lev is a Paris-based illustrator and street artist whose practice moves between wall painting, editorial imagery, and digital work. (@antonialev)",
        "storyFullText": "Antonia Lev is a Paris-based illustrator and street artist whose practice moves between wall painting, editorial imagery, and digital work. Her images are graphic and narrative, with figures and scenes that hold up at mural scale while still giving the eye something to follow close up.\n\nThe work has a storybook pulse, but it is not soft in a decorative way. Lines stay confident, characters carry attitude, and the compositions often feel like fragments of a larger scene caught mid-movement.\n\nRecent public material points to a 2025 mural project, The Dance of Blooming, connected to Mural City activity in the Paris region. Older public material also shows her moving between festival walls and illustration platforms, which fits the range of the practice.\n\nWhat makes Lev's work engaging is the way it treats public space as a narrative surface. A wall is not just scale; it is a place where a character, a gesture, or a small fiction can suddenly belong to the street.",
        "activeSince": "Behance lists professional start 4 Nov 2011 (verify on live profile)",
    },
    "aviv-shamir": {
        "heroHook": "Aviv Shamir is a Tel Aviv illustrator who keeps the process visible. (@avivos_91)",
        "storyFullText": "Aviv Shamir is a Tel Aviv illustrator who keeps the process visible. Sketches, finished pieces, and mid-thought experiments share the same feed \u2014 faces, humor, and the texture of daily city life.\n\nThe transparency is part of the appeal: you see the hand, the hesitation, and the result in one scroll. The point is not to make Aviv Shamir easy to categorize; the work is more interesting because it keeps moving between image, object, and atmosphere. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThe work does not need a heavy explanation to hold attention. It earns that attention through pace, pressure, color, and a clear sense of where the artist wants the eye to land.",
        "activeSince": "",
    },
    "beto-val": {
        "heroHook": "Beto Valencia makes digital collages from vintage scientific illustration \u2014 birds, bones, botanical plates \u2014 and arranges them into ecosystems where nothing quite follows the\u2026 (@elbetoval)",
        "storyFullText": "Beto Valencia makes digital collages from vintage scientific illustration \u2014 birds, bones, botanical plates \u2014 and arranges them into ecosystems where nothing quite follows the original logic. Every piece feels like a cabinet of curiosities tipped sideways.\n\nThe surface matters as much as the subject, with fragments arranged until the image feels discovered rather than assembled. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary. Across formats, the work is most alive when it lets polish and personality sit together: clean enough to read fast, human enough to keep its edges.\n\nThere is enough clarity to enter the image quickly, and enough friction to keep looking once the subject has settled.\n\nAcross formats, the practice is less about repeating a signature trick than about returning to a set of visual instincts and testing what they can carry next.",
        "activeSince": "Public practice accelerated during pandemic per elbetoval.com blog essays",
    },
    "carsten-gueth": {
        "heroHook": "Carsten Gueth studied architecture and urban planning in Stuttgart before spending fifteen years in graphic design for cultural institutions \u2014 museums, festivals, publishers. (@die_doing)",
        "storyFullText": "Carsten Gueth studied architecture and urban planning in Stuttgart before spending fifteen years in graphic design for cultural institutions \u2014 museums, festivals, publishers. His independent practice publishes as Die Doing.\n\nThe work is bold, occasionally absurd, and built to read from across a room. Recent recognition from ADC, Red Dot, and Palau de la M\u00fasica Catalana suggests the pivot was the right call. Stuttgart enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land.\n\nIn 2025, a solo project, Rituals for the Unknown, kept the practice active at Palau de la M\u00fasica Catalana in Barcelona, Spain. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThat mix of accessibility and discipline is what keeps the practice from feeling decorative. The surface is inviting, but the choices underneath are specific.",
        "activeSince": "~15 years agency graphic design before independent art (Artinrug); mural practice since 2010 cited on related pages",
    },
    "chubby-nida": {
        "heroHook": "Chubby Nida is a Bangkok illustrator whose round, gentle figures carry social commentary without announcing it. (@chubbynida)",
        "storyFullText": "Chubby Nida is a Bangkok illustrator whose round, gentle figures carry social commentary without announcing it. Editorial and personal pieces share the same approach: approachable shapes, colors you want to keep, ideas that land after the smile.\n\nShe is part of a generation redefining what \"cute\" can argue for in public. Bangkok enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nAcross formats, the work is most alive when it lets polish and personality sit together: clean enough to read fast, human enough to keep its edges.\n\nThere is enough clarity to enter the image quickly, and enough friction to keep looking once the subject has settled.",
        "activeSince": "~12 years professional per Art of Th interview (2023)",
    },
    "cokorda-martin": {
        "heroHook": "Cokorda Martin grew up in Klungkung inside a family of makers. (@treasurecult.work)",
        "storyFullText": "Cokorda Martin grew up in Klungkung inside a family of makers. Traditional Balinese motifs \u2014 ritual pattern, temple color, mythic reference \u2014 are his raw material, but he doesn't treat them as historical objects.\n\nThey show up in album art, brand collaborations with Caf\u00e9 Kitsun\u00e9 and Uniqlo, and editorial work for international clients. Island craft meeting global briefs, without losing anything in the translation. Bali enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land.\n\nIn 2024, the practice stayed active through Group: Crossfade (with Refli, Yoel Kristiandi), Draft Land Singapore \u2014 7 Oct \u2013 22 Dec 2024. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThe best way into the work is through its decisions: what gets simplified, what stays strange, and where the image leaves room for the viewer to finish the thought.",
        "activeSince": "Career start 2013; born Klungkung 1995 (Timeout interview, Ana-tomy journal)",
    },
    "crackthetoy": {
        "heroHook": "Crack works as Crackthetoy \u2014 a graffiti artist, toy designer, and digital illustrator based in Indonesia. (@crackthetoy)",
        "storyFullText": "Crack works as Crackthetoy \u2014 a graffiti artist, toy designer, and digital illustrator based in Indonesia. The characters are collectible and slightly mischievous, living between product fantasy and mural scale.\n\nBold outlines, candy color, stories you read in one glance. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThe best way into the work is through its decisions: what gets simplified, what stays strange, and where the image leaves room for the viewer to finish the thought.\n\nThere is enough clarity to enter the image quickly, and enough friction to keep looking once the subject has settled.",
        "activeSince": "",
    },
    "cubi-boumclap": {
        "heroHook": "Cubi Boumclap works from southwestern France as an illustrator, comic artist, and designer who treats the screen and the alley as close cousins. (cubi_boumclap)",
        "storyFullText": "Cubi Boumclap works from southwestern France as an illustrator, comic artist, and designer who treats the screen and the alley as close cousins. The line is fast, direct, and honest about commerce \u2014 open for studios, publishers, and anyone who needs graphics with street timing.\n\nHis early years were shaped by the La Streetarterie collective; the work still carries that energy. Agen enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThe best way into the work is through its decisions: what gets simplified, what stays strange, and where the image leaves room for the viewer to finish the thought.",
        "activeSince": "Behance member since 2012; La Streetarterie core member since 2015 (per regional press)",
    },
    "dawal": {
        "heroHook": "Dawal is a Paris-based street artist who learned the city by painting it. (@_dawal)",
        "storyFullText": "Dawal is a Paris-based street artist who learned the city by painting it. His work begins with what most people walk past: cracked plaster, peeling paint, chipped corners, and aging surfaces that already carry a kind of accidental drawing.\n\nInto those marks he places small surreal scenes, turning damaged walls into pocket-sized stages. The result is intimate for street work: you do not just see the image from across the road, you discover it at pavement distance, almost like the city has hidden a thought in plain sight.\n\nRecent activity keeps that street instinct alive. In 2025, press focused on his miniature interventions across Paris, and in 2026 his solo project Reve Lucide at Galerie Artistik Rezo brought the same dream logic into a gallery context.\n\nThe appeal is not just the illusion. It is the way Dawal listens to the surface before painting, letting the wall decide part of the composition and keeping the finished work tied to the place that made it possible.",
        "activeSince": "",
    },
    "dima-korma": {
        "heroHook": "Dima Korma is a Berlin-based muralist, originally from Israel, who studied visual communication at Shenkar. (@dimakorma)",
        "storyFullText": "Dima Korma is a Berlin-based muralist, originally from Israel, who studied visual communication at Shenkar. His walls layer paste, paint, and type fragments over the existing character of a building.\n\nAbstract, but not empty \u2014 each surface feels like it's describing a climate the space was already hinting at. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nAcross formats, the work is most alive when it lets polish and personality sit together: clean enough to read fast, human enough to keep its edges.\n\nThere is enough clarity to enter the image quickly, and enough friction to keep looking once the subject has settled.",
        "activeSince": "",
    },
    "eden-kalif": {
        "heroHook": "Eden Kalif is an illustrator and tattoo artist who graduated Bezalel and kept both practices going in parallel. (_e_d_e_n_)",
        "storyFullText": "Eden Kalif is an illustrator and tattoo artist who graduated Bezalel and kept both practices going in parallel. His line does the heavy lifting \u2014 faces, hands, and symbols with almost nothing extra.\n\nTel Aviv enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary. What gives the practice its pull is the balance between immediate charm and careful construction; the image opens quickly, then keeps revealing how it was built.\n\nThere is enough clarity to enter the image quickly, and enough friction to keep looking once the subject has settled.\n\nAcross formats, the practice is less about repeating a signature trick than about returning to a set of visual instincts and testing what they can carry next.",
        "activeSince": "Post-Bezalel professional practice (Artinrug, GoodMood artist pages)",
    },
    "elfassi": {
        "heroHook": "Elfassi graduated Shenkar in visual communication and never picked just one surface. (@elfassi)",
        "storyFullText": "Elfassi graduated Shenkar in visual communication and never picked just one surface. Embroidery, mural paint, digital line, and music posters all come from the same hand and the same graphic sensibility.\n\nThe materials change; the voice stays consistent. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThat mix of accessibility and discipline is what keeps the practice from feeling decorative. The surface is inviting, but the choices underneath are specific.\n\nThere is enough clarity to enter the image quickly, and enough friction to keep looking once the subject has settled.",
        "activeSince": "",
    },
    "emelio-cerezo": {
        "heroHook": "Emilio Cerezo grew up in Murcia, studied fine arts in Granada, and ran under graffiti aliases until 2012 when he started putting his own name on walls. (@emiliocerezo)",
        "storyFullText": "Emilio Cerezo grew up in Murcia, studied fine arts in Granada, and ran under graffiti aliases until 2012 when he started putting his own name on walls. The academic training paid off in specific ways \u2014 figure, landscape, and mural scale now share a painterly attention to mood over representation.\n\nHe wants people to experience his murals the way they experience landscape or music: not as a message, but as an atmosphere. He still tattoos between murals, which probably explains the line quality. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit.\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThat mix of accessibility and discipline is what keeps the practice from feeling decorative. The surface is inviting, but the choices underneath are specific.",
        "activeSince": "Graffiti since 2001; fine arts University of Granada 2004\u20132009; postgraduate drawing 2009\u20132010 (UrbanPresents interview)",
    },
    "erezoo": {
        "heroHook": "Erez Sameach works as Erezoo from Haifa, where illustration, graphic design, and graffiti are treated as the same practice rather than three separate disciplines. (@erezoo)",
        "storyFullText": "Erez Sameach works as Erezoo from Haifa, where illustration, graphic design, and graffiti are treated as the same practice rather than three separate disciplines. Born in Carmiel, trained at Wizo, he helped build the SIRA collective alongside relatives who paint the same streets.\n\nThe output is loud, coastal, and rooted in the city's cultural calendar. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThe best way into the work is through its decisions: what gets simplified, what stays strange, and where the image leaves room for the viewer to finish the thought.",
        "activeSince": "Born 1990 Carmiel; Vizcoa Haifa visual communication graduate (Dror Hadadi + erezoo.com about)",
    },
    "ezra-baderman": {
        "heroHook": "Ezra Baderman was born in Paris, grew up in London, trained at John Cass and Bezalel, and now works in Lisbon. (@ezrabaderman)",
        "storyFullText": "Ezra Baderman was born in Paris, grew up in London, trained at John Cass and Bezalel, and now works in Lisbon. His practice \u2014 collage, painting, UV work, salvaged street posters from Tel Aviv walls \u2014 is shaped by all of that movement.\n\nFragments of political imagery get rearranged into something quieter and stranger. The street is both material and argument. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit.\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThe best way into the work is through its decisions: what gets simplified, what stays strange, and where the image leaves room for the viewer to finish the thought.",
        "activeSince": "",
    },
    "facio": {
        "heroHook": "Tom\u00e1s Facio was born in 1990 in Merlo, studied at the National University of Arts in Buenos Aires from 2013, and paints walls across Argentina and beyond. (@tomas_facio)",
        "storyFullText": "Tom\u00e1s Facio was born in 1990 in Merlo, studied at the National University of Arts in Buenos Aires from 2013, and paints walls across Argentina and beyond. Figures, typography, and local symbols interlock in murals that read from a block away and hold up closer.\n\nA designer's attention to silhouette, a muralist's appetite for scale. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. In 2024, the practice stayed active through Mural (street art program), Merlo, Argentina.\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nAcross formats, the work is most alive when it lets polish and personality sit together: clean enough to read fast, human enough to keep its edges.",
        "activeSince": "UNA art studies from 2013; born 1990 (Street Art Cities bio)",
    },
    "frederique-mati": {
        "heroHook": "Frederique Matti is an Amsterdam-based illustrator, art director, and painter whose practice has grown out of more than a decade of freelance visual work. (@frederique.png)",
        "storyFullText": "Frederique Matti is an Amsterdam-based illustrator, art director, and painter whose practice has grown out of more than a decade of freelance visual work. Her images tend to be calm at first glance: restrained palette, clear silhouettes, and characters who seem comfortable inside their own weather.\n\nThat calm is not empty. Editorial, branding, painting, and object-based projects all show a designer's sense of structure, but the recent work keeps moving toward a warmer painterly voice.\n\nHer public site notes clients including Google, Uber, Spotify, GitHub, and Dropbox, plus recent selected work such as a 2023 Hoxton Amsterdam presentation and a hand-painted Tivoli speaker project in 2024.\n\nWhat holds the work together is not a single subject, but a tone: observant, balanced, slightly dry, and attentive to the small gestures that make a character feel lived-in.",
        "activeSince": "10+ years experience per frederiquematti.com",
    },
    "geometric-bang": {
        "heroHook": "Mattia Botta has been working as Geometric Bang since the late 1990s, starting in graffiti and moving steadily toward a practice that now spans murals, illustration\u2026 (@geometricbang)",
        "storyFullText": "Mattia Botta has been working as Geometric Bang since the late 1990s, starting in graffiti and moving steadily toward a practice that now spans murals, illustration, tattooing, and canvas. Born in Lodi, based in Florence, he works with pencil, spray, and ink across a graphic vocabulary built on bold color blocks with human warmth underneath.\n\nEuropean festivals and Asian walls share space on his calendar. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. In 2024, the practice stayed active through Wall projects documented, Rome, Genoa, and Tokyo, Japan.\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.",
        "activeSince": "Graffiti since late 1990s per Varsi / Wood\u2019d profiles",
    },
    "hedof": {
        "heroHook": "Rick Berkelmans runs Hedof as a one-person studio where drawing and printmaking stay close. (@hedof)",
        "storyFullText": "Rick Berkelmans runs Hedof as a one-person studio where drawing and printmaking stay close. Animals, pattern, and pop culture wink at you from work made for Nike, IKEA, The New York Times, and Google.\n\nThe work is genuinely warm and graphically sharp at the same time, which is harder than it looks. Breda enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThat mix of accessibility and discipline is what keeps the practice from feeling decorative. The surface is inviting, but the choices underneath are specific.\n\nThere is enough clarity to enter the image quickly, and enough friction to keep looking once the subject has settled.",
        "activeSince": "",
    },
    "hen-macabi": {
        "heroHook": "Hen Macabi is an Israeli illustrator and art director whose typography-first work has shaped some of the country's most recognizable pop moments. (@henmacabi)",
        "storyFullText": "Hen Macabi is an Israeli illustrator and art director whose typography-first work has shaped some of the country's most recognizable pop moments. His cover for Netta Barzilai's \"Bassa Sababa\" \u2014 released in the lead-up to her Eurovision win \u2014 is the most visible example.\n\nHe trained at Shenkar. The AlefAlefAlef project, a graphic tribute to 70 years of Israeli cinema done in VHS-cover logic, shows what he does with more room. The work understands graphic impact: shape, type, and color arrive quickly, then leave enough tension to keep looking.\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThe best way into the work is through its decisions: what gets simplified, what stays strange, and where the image leaves room for the viewer to finish the thought.",
        "activeSince": "",
    },
    "iain-macarthur": {
        "heroHook": "Iain Macarthur is a London illustrator who builds portraits out of filigree \u2014 faces that dissolve into wildlife, geometry, and surreal detail. (@iain.macarthur)",
        "storyFullText": "Iain Macarthur is a London illustrator who builds portraits out of filigree \u2014 faces that dissolve into wildlife, geometry, and surreal detail. He grew up in Swindon, studied at Swindon College, and has been freelancing from London since 2009.\n\nMusic packaging, apparel, and gallery work share the same marathon patience. The reward is density you can actually get lost in. London enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land.\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nAcross formats, the work is most alive when it lets polish and personality sit together: clean enough to read fast, human enough to keep its edges.",
        "activeSince": "Self-employed illustrator since Jan 2009 (LinkedIn)",
    },
    "igal-talianski": {
        "heroHook": "Igal Talianski works from Haifa in collage and mixed media, building images from paper, color, fragments, and found texture. (@iigalskii)",
        "storyFullText": "Igal Talianski works from Haifa in collage and mixed media, building images from paper, color, fragments, and found texture. The surfaces feel constructed rather than polished flat, which is exactly where their warmth comes from.\n\nHis work has also moved through climbing and local visual culture, where tactile material and direct graphic impact matter. Whether the format is a wall, an object, or a framed piece, the invitation is similar: step closer and notice what has been kept, cut, layered, or left rough.\n\nPublic exhibition history connects the practice to Israeli illustration and repurposed-book contexts, including LaCulture illustration programming and Edmond de Rothschild Center activity in Tel Aviv.\n\nThe strongest part of the work is its honesty about materials. You can feel the decisions in the surface, and that gives the images a physical presence that clean digital finish would flatten.",
        "activeSince": "",
    },
    "igor-mikutski": {
        "heroHook": "Igor Mikutski is a painter who treats social media video the way older generations used sketchbooks \u2014 brush tests, half-finished canvases, process posted as it happens. (@igor.mikutski)",
        "storyFullText": "Igor Mikutski is a painter who treats social media video the way older generations used sketchbooks \u2014 brush tests, half-finished canvases, process posted as it happens. The work is large-scale, figurative, and acrylic-on-paper.\n\nThe finished pieces carry the pulse of being made in public. The point is not to make Igor Mikutski easy to categorize; the work is more interesting because it keeps moving between image, object, and atmosphere. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nBecause the public trail is narrow, the profile keeps to visible practice rather than filling gaps with unsupported biography.",
        "activeSince": "",
    },
    "jake-ac-art": {
        "heroHook": "Jack AC Art builds a small universe where illustration meets greeting-card wit. (@jack_ac_art)",
        "storyFullText": "Jack AC Art builds a small universe where illustration meets greeting-card wit. The tone is intimate \u2014 phrases you'd send a friend, pictures you'd hang in a kitchen.\n\nMade to be held, mailed, and kept. The point is not to make Jake Ac art easy to categorize; the work is more interesting because it keeps moving between image, object, and atmosphere. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nBecause the public trail is narrow, the profile keeps to visible practice rather than filling gaps with unsupported biography.",
        "activeSince": "",
    },
    "jennypo-art": {
        "heroHook": "Jenny Pokryvailo is a tattooist and illustrator whose line never forgets skin. (@jennypoart)",
        "storyFullText": "Jenny Pokryvailo is a tattooist and illustrator whose line never forgets skin. Whether the surface is body or paper, the drawing stays decisive \u2014 ornament, narrative, and negative space in careful balance.\n\nFans follow for the same reason clients book: every mark earns its place. The point is not to make Jennypo Art easy to categorize; the work is more interesting because it keeps moving between image, object, and atmosphere. In 2024, the practice stayed active through Imperial Hotel Wonderland 03 (with Yaara Sachs and the Imperial Group), Tel Aviv, Israel.\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThat mix of accessibility and discipline is what keeps the practice from feeling decorative. The surface is inviting, but the choices underneath are specific.",
        "activeSince": "",
    },
    "jerome-masi": {
        "heroHook": "Jerome Masi studied at Emile-Cohl in Lyon, moved through game studios and motion design, and now works from Annecy as a full-time illustrator. (@jerome.masi)",
        "storyFullText": "Jerome Masi studied at Emile-Cohl in Lyon, moved through game studios and motion design, and now works from Annecy as a full-time illustrator. That route matters: his images have the control of someone who understands production, but they leave enough quiet for interpretation.\n\nCommercial projects for transport, watch, and telecom clients sit beside personal acrylic paintings. Across both, the palette tends to stay restrained and the composition carefully staged, as if each image is a memory held just before it becomes too clear.\n\nInterviews and portfolio material describe a practice interested in leaving space for the viewer. Even when the subject is direct, the mood is open-ended; Masi lets atmosphere do part of the storytelling.\n\nThe work is strongest when technique disappears into feeling. You sense the design training underneath, but what stays with you is the pause, the silence, and the small emotional weather inside the image.",
        "activeSince": "Graphic studio founded 2006 (Lyon, per LM); full-time illustration with Creasenso ~10 years as of Mar 2022; Emile-Cohl (Lyon) arts appliqu\u00e9s",
    },
    "kaka-chazz": {
        "heroHook": "Cassiano Henrique C\u00e2ndido, known as Kak\u00e1 Chazz, has been painting walls since 2008 in and around Tr\u00eas Pontas in southern Brazil. (@kaka.chazz)",
        "storyFullText": "Cassiano Henrique C\u00e2ndido, known as Kak\u00e1 Chazz, has been painting walls since 2008 in and around Tr\u00eas Pontas in southern Brazil. His murals translate everyday Minas scenes \u2014 work, faith, family \u2014 into something monumental that neighbors actually recognize.\n\nThe style bridges classical figure drawing and graffiti scale without forcing them to pretend they're the same thing. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. In 2025, the practice stayed active through Large-scale public mural (72 m\u00b2) honoring Milton Nascimento, Tr\u00eas Pontas, Minas Gerais, Brazil.\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThe work does not need a heavy explanation to hold attention. It earns that attention through pace, pressure, color, and a clear sense of where the artist wants the eye to land.",
        "activeSince": "Visual practice since 2008; born Tr\u00eas Pontas 1989 (kakachazz.com.br biografia)",
    },
    "keya-tama": {
        "heroHook": "Keya Tama was born in Cape Town in 1997 and now works from New York. (@keyatama)",
        "storyFullText": "Keya Tama was born in Cape Town in 1997 and now works from New York. Her practice braids ancestral symbolism with graphic minimalism \u2014 each piece asking how much you can strip away and still say something complete.\n\nShe has shown with Hashimoto Contemporary in New York and Subliminal Projects in Los Angeles, painted murals at festivals and institutions across Africa and Europe, and collaborated with the Royal Delft Museum on ceramic work. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. The best way into the work is through its decisions: what gets simplified, what stays strange, and where the image leaves room for the viewer to finish the thought.\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.",
        "activeSince": "Born Cape Town 1997; mural travel with parent artist per SDVoyager (2019)",
    },
    "kymo-one": {
        "heroHook": "Kymo One is a Belgian muralist trained in graphic illustration who never gave up spray paint. (kymo_one)",
        "storyFullText": "Kymo One is a Belgian muralist trained in graphic illustration who never gave up spray paint. Chains, roses, smoke, and industrial romanticism repeat across European walls \u2014 old-master drama at graffiti velocity.\n\nReadable from the sidewalk and worth getting closer to. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThe best way into the work is through its decisions: what gets simplified, what stays strange, and where the image leaves room for the viewer to finish the thought.\n\nThere is enough clarity to enter the image quickly, and enough friction to keep looking once the subject has settled.",
        "activeSince": "Active in documented murals from at least 2018 onward per Dutch Wikipedia project list",
    },
    "laura-fridman": {
        "heroHook": "Laura Fridman is French, studied economics at Yale, danced with the Israel Ballet, and then started painting. (@laura_fridman_art)",
        "storyFullText": "Laura Fridman is French, studied economics at Yale, danced with the Israel Ballet, and then started painting. Her figurative work exaggerates hands and necks while keeping faces photographic \u2014 a tension that feels physical, like the body is working through something.\n\nShe has shown in Tel Aviv, Paris, and Barcelona. Tel Aviv enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land. In 2024, a solo project, Elegance Intemporelle, kept the practice active at Paris in France.\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThe best way into the work is through its decisions: what gets simplified, what stays strange, and where the image leaves room for the viewer to finish the thought.",
        "activeSince": "",
    },
    "levi-jacobs": {
        "heroHook": "Levi Jacobs is a Rotterdam illustrator and animator who treats image-making like staged cinema. (@levijacobss)",
        "storyFullText": "Levi Jacobs is a Rotterdam illustrator and animator who treats image-making like staged cinema. Light, cast, props, and atmosphere all feel chosen, which gives even a simple scene a sense of hidden narrative.\n\nHe studied illustration at St. Joost and has worked freelance since 2010. The work is slightly noir, slightly surreal, and consistently human, with everyday settings pushed just far enough to become memorable.\n\nRecent public activity in the research includes Playgrounds programming, including In Motion Rotterdam in 2023. That context fits a practice where still illustration and motion thinking often sit close together.\n\nJacobs' images are strongest when they leave a question in the room. You feel the story before you know it, then start reading the composition for clues.",
        "activeSince": "Freelance illustration since 2010 (LinkedIn); BDes Illustration St. Joost 2006\u20132010",
    },
    "linda-baritski": {
        "heroHook": "Linda Baritski spent years inside major studios before SEASONOFVICTORY became her public name. (@seasonofvictory)",
        "storyFullText": "Linda Baritski spent years inside major studios before SEASONOFVICTORY became her public name. The independent practice landed quickly \u2014 a Kiehl's global campaign across 48 locations in 2022\u201323 was an early sign.\n\nThe work is color-committed and character-forward, shaped by a background in art direction that knows exactly how to make things land, whether on packaging or a wall. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThe work does not need a heavy explanation to hold attention. It earns that attention through pace, pressure, color, and a clear sense of where the artist wants the eye to land.",
        "activeSince": "",
    },
    "lobster-robin": {
        "heroHook": "Lobster Robin is a Belgian painter and street artist with a background in illustration and animation. (@lobster_robin)",
        "storyFullText": "Lobster Robin is a Belgian painter and street artist with a background in illustration and animation. The characters feel like graphic novels escaped onto brick \u2014 saturated outlines, narrative freeze-frames, enough warmth on the surface to bring in a wide audience and enough timing underneath to hold them.\n\nThat sense of timing stays visible even in still images: the composition feels paused rather than frozen. In 2024, the practice stayed active through Northwest Walls festival participation (mural program), Belgium. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nScale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit.",
        "activeSince": "",
    },
    "loreta-isac": {
        "heroHook": "Loreta Isac is a Bucharest-based illustrator and animator who grew up in Iasi and studied art before building a practice around dreamlike narrative images. (@loreta_isac)",
        "storyFullText": "Loreta Isac is a Bucharest-based illustrator and animator who grew up in Iasi and studied art before building a practice around dreamlike narrative images. She has described her own world with the phrase \"once upon a dreamer,\" and the work really does move with that half-awake logic.\n\nHer illustrations and animations move between editorial commissions, music-related work, and personal pieces where figures seem caught in the middle of thought. Color, shape, and motion are used less for spectacle than for atmosphere.\n\nRecent exhibition research includes the 2024 group project Home A Sense of Belonging in Amsterdam, following earlier motion and illustration contexts in Beijing, Wroclaw, Timisoara, and Bucharest.\n\nWhat keeps the work interesting is its emotional suspension. Isac lets the drawing breathe just long enough for the viewer to wonder what happened before the image, and what might happen after.",
        "activeSince": "",
    },
    "maalavidaa": {
        "heroHook": "Alycia Rainaud built Maalavidaa around a 2018 thesis on the role of psychology in design. (@maalavidaa)",
        "storyFullText": "Alycia Rainaud built Maalavidaa around a 2018 thesis on the role of psychology in design. The neon gradients and saturated abstraction aren't decorative \u2014 they're the argument: color as a tool for emotional regulation, rhythm as something you can actually feel.\n\nThe work doesn't tell you how to feel. It gives you something to feel with. That sense of timing stays visible even in still images: the composition feels paused rather than frozen.\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThe best way into the work is through its decisions: what gets simplified, what stays strange, and where the image leaves room for the viewer to finish the thought.\n\nThere is enough clarity to enter the image quickly, and enough friction to keep looking once the subject has settled.",
        "activeSince": "Studio Maalavidaa Inc. founded 2016 (LinkedIn); DSAA graphic design MA 2018 per maalavidaa.com/about",
    },
    "mameko-maeda": {
        "heroHook": "Mameko Maeda is a Tokyo illustrator born in 1993 who turned professional in 2020. (@mameko_maeda)",
        "storyFullText": "Mameko Maeda is a Tokyo illustrator born in 1993 who turned professional in 2020. Her figures carry gentle humor and precise ink \u2014 editorial and personal projects sharing an affection for youth culture, fashion, and quiet punchlines.\n\nShe makes cute feel smart and smart feel approachable. Tokyo enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land. In 2024, the practice stayed active through Solo: My Romantic Karma, TRUNK(HOTEL) CAT STREET, Shibuya, Tokyo.\n\nThe work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThat mix of accessibility and discipline is what keeps the practice from feeling decorative. The surface is inviting, but the choices underneath are specific.",
        "activeSince": "Professional illustrator from 2020; born Tokyo 1993 (mameko-maeda.com EN)",
    },
    "marc-david-spengler": {
        "heroHook": "Marc David Spengler graduated communication design from Stuttgart's state academy in 2022 and immediately started working with clients who care about craft: Herm\u00e8s, The New\u2026 (@_marcdavid_)",
        "storyFullText": "Marc David Spengler graduated communication design from Stuttgart's state academy in 2022 and immediately started working with clients who care about craft: Herm\u00e8s, The New Yorker, Google, Vans, The Atlantic. The work moves between hand media and screen without losing its texture \u2014 ink that still feels considered even when the final file is digital.\n\nHe is represented in North America and China. Stuttgart enters the work as rhythm rather than scenery: light, pacing, and local texture shape the way the images land. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThat mix of accessibility and discipline is what keeps the practice from feeling decorative. The surface is inviting, but the choices underneath are specific.",
        "activeSince": "Studio since Oct 2015 (LinkedIn); diploma communication design 2022, Staatliche Akademie der Bildenden K\u00fcnste Stuttgart (studio site)",
    },
    "marylou-faure": {
        "heroHook": "Marylou Faure studied art direction in Paris and moved to London in 2012. (@maryloufaure)",
        "storyFullText": "Marylou Faure studied art direction in Paris and moved to London in 2012. She built a practice around figures who stare back without eyes yet feel completely present.\n\nThe work is deliberately cheeky \u2014 saturated color, poster-graphic bones, characters who own their space. She has made solo shows and brand campaigns for McLaren F1 and Kiehl's without softening either end. The work understands graphic impact: shape, type, and color arrive quickly, then leave enough tension to keep looking.\n\nIn 2024, a solo project, It's All About Me, kept the practice active at E03 in Beijing, China. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThat mix of accessibility and discipline is what keeps the practice from feeling decorative. The surface is inviting, but the choices underneath are specific.",
        "activeSince": "Freelance illustration ~2015\u20132016 per It\u2019s Nice That (2016)",
    },
    "mathew-gagnon": {
        "heroHook": "Matthew Gagnon is a Montreal artist who uses walls and panels as stages for symbolic narrative. (@mattjgag)",
        "storyFullText": "Matthew Gagnon is a Montreal artist who uses walls and panels as stages for symbolic narrative. Figures, animals, and pattern stack into scenes that feel borrowed from dreams and collective memory.\n\nThe palette is bold, the drawing disciplined \u2014 the same storyteller working at street scale and gallery scale. Scale matters, but so does the close read: the strongest work keeps small marks, odd characters, and surface decisions alive after the first hit. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThe best way into the work is through its decisions: what gets simplified, what stays strange, and where the image leaves room for the viewer to finish the thought.\n\nThere is enough clarity to enter the image quickly, and enough friction to keep looking once the subject has settled.",
        "activeSince": "",
    },
    "max-diamond": {
        "heroHook": "Max Diamond makes posters that understand fandom from the inside. (@maxdiamond52)",
        "storyFullText": "Max Diamond makes posters that understand fandom from the inside. Each one leads with a single clean idea \u2014 the visual logic of an album cover applied to characters and moments people already carry in their heads.\n\nMeant to read across a room and reward a closer look. The work understands graphic impact: shape, type, and color arrive quickly, then leave enough tension to keep looking. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nThat mix of accessibility and discipline is what keeps the practice from feeling decorative. The surface is inviting, but the choices underneath are specific.\n\nThere is enough clarity to enter the image quickly, and enough friction to keep looking once the subject has settled.",
        "activeSince": "",
    },
    "moritz-adam-schmitt": {
        "heroHook": "Moritz Adam Schmitt spent a year posting one icon a day to Instagram. (@moritz.adam.schmitt)",
        "storyFullText": "Moritz Adam Schmitt spent a year posting one icon a day to Instagram. That discipline turned into an invitation to Adobe MAX, then into a freelance career with clients like Adobe, Microsoft, Xbox, Porsche, and Samsung.\n\nHis process starts with iPad sketches and ends in tight vector work \u2014 bold outlines, flat color, the attitude of a good street poster without any of the mess. The work understands graphic impact: shape, type, and color arrive quickly, then leave enough tension to keep looking. The work is strongest where the hand, the idea, and the chosen surface all feel equally necessary.\n\nAcross formats, the work is most alive when it lets polish and personality sit together: clean enough to read fast, human enough to keep its edges.",
        "activeSince": "Freelance illustration from 2016 (Adobe blog); prior study Mediendesign Rheinische Fachhochschule K\u00f6ln",
    },
}
