/**
 * Shopify Content Sync Script
 * 
 * Fetches all static content from the Shopify store and writes it to
 * content/shopify-content.ts for use in the app.
 * 
 * Run with: npx ts-node scripts/sync-shopify-content.ts
 * Or: npx tsx scripts/sync-shopify-content.ts
 */

import * as fs from 'fs'
import * as path from 'path'

// We need to set up environment variables before importing modules
import * as dotenv from 'dotenv'
dotenv.config({ path: '.env.local' })

// Now import the Shopify modules
import { getMainMenu, getFooterMenu, transformMenuToNavigation, transformMenuToFooterSections, type NavigationItem } from '../lib/shopify/menus'
import { getAllPages, type ShopifyPage } from '../lib/shopify/pages'
import { getBlogs, getBlogWithArticles, fetchAllArticles, type ShopifyArticle, type ShopifyBlog } from '../lib/shopify/blogs'

// =============================================================================
// TYPES FOR SYNCED CONTENT
// =============================================================================

interface SyncedNavigation {
  mainMenu: NavigationItem[]
  footerSections: Array<{
    title: string
    links: Array<{ label: string; href: string }>
  }>
}

interface SyncedPage {
  handle: string
  title: string
  body: string
  bodySummary: string
  updatedAt: string
}

interface SyncedArticle {
  handle: string
  blogHandle: string
  title: string
  excerpt: string | null
  contentHtml: string
  imageUrl: string | null
  imageAlt: string | null
  publishedAt: string
  authorName: string
  tags: string[]
}

interface SyncedContent {
  navigation: SyncedNavigation
  pages: Record<string, SyncedPage>
  articles: SyncedArticle[]
  syncedAt: string
}

// =============================================================================
// SYNC FUNCTIONS
// =============================================================================

async function syncNavigation(): Promise<SyncedNavigation> {
  console.log('📋 Syncing navigation menus...')
  
  const [mainMenu, footerMenu] = await Promise.all([
    getMainMenu(),
    getFooterMenu(),
  ])
  
  const mainNavigation = transformMenuToNavigation(mainMenu)
  const footerSections = transformMenuToFooterSections(footerMenu)
  
  console.log(`   ✓ Main menu: ${mainNavigation.length} items`)
  console.log(`   ✓ Footer sections: ${footerSections.length} sections`)
  
  return {
    mainMenu: mainNavigation,
    footerSections,
  }
}

async function syncPages(): Promise<Record<string, SyncedPage>> {
  console.log('📄 Syncing pages...')
  
  const pages = await getAllPages()
  const pagesMap: Record<string, SyncedPage> = {}
  
  for (const page of pages) {
    pagesMap[page.handle] = {
      handle: page.handle,
      title: page.title,
      body: page.body,
      bodySummary: page.bodySummary,
      updatedAt: page.updatedAt,
    }
  }
  
  console.log(`   ✓ Synced ${pages.length} pages`)
  pages.forEach(p => console.log(`     - ${p.handle}`))
  
  return pagesMap
}

async function syncArticles(): Promise<SyncedArticle[]> {
  console.log('📰 Syncing blog articles...')
  
  const articles = await fetchAllArticles()
  
  const syncedArticles: SyncedArticle[] = articles.map(article => ({
    handle: article.handle,
    blogHandle: article.blog.handle,
    title: article.title,
    excerpt: article.excerpt,
    contentHtml: article.contentHtml,
    imageUrl: article.image?.url || null,
    imageAlt: article.image?.altText || null,
    publishedAt: article.publishedAt,
    authorName: article.author.name,
    tags: article.tags,
  }))
  
  console.log(`   ✓ Synced ${syncedArticles.length} articles`)
  
  return syncedArticles
}

// =============================================================================
// CONTENT GENERATOR
// =============================================================================

function generateContentFile(content: SyncedContent): string {
  return `/**
 * Shopify Content (Auto-generated)
 * 
 * This file is automatically generated by scripts/sync-shopify-content.ts
 * Do not edit this file directly - run the sync script instead.
 * 
 * Last synced: ${content.syncedAt}
 */

// =============================================================================
// TYPE DEFINITIONS
// =============================================================================

export interface NavigationItem {
  label: string
  href: string
  children?: NavigationItem[]
}

export interface FooterSection {
  title: string
  links: Array<{ label: string; href: string }>
}

export interface SyncedPage {
  handle: string
  title: string
  body: string
  bodySummary: string
  updatedAt: string
}

export interface SyncedArticle {
  handle: string
  blogHandle: string
  title: string
  excerpt: string | null
  contentHtml: string
  imageUrl: string | null
  imageAlt: string | null
  publishedAt: string
  authorName: string
  tags: string[]
}

// =============================================================================
// NAVIGATION
// =============================================================================

export const mainNavigation: NavigationItem[] = ${JSON.stringify(content.navigation.mainMenu, null, 2)}

export const footerSections: FooterSection[] = ${JSON.stringify(content.navigation.footerSections, null, 2)}

// =============================================================================
// PAGES
// =============================================================================

export const pages: Record<string, SyncedPage> = ${JSON.stringify(content.pages, null, 2)}

/**
 * Get a page by handle
 */
export function getPage(handle: string): SyncedPage | undefined {
  return pages[handle]
}

/**
 * Check if a page exists
 */
export function hasPage(handle: string): boolean {
  return handle in pages
}

// =============================================================================
// BLOG ARTICLES
// =============================================================================

export const articles: SyncedArticle[] = ${JSON.stringify(content.articles, null, 2)}

/**
 * Get an article by handle
 */
export function getArticle(handle: string): SyncedArticle | undefined {
  return articles.find(a => a.handle === handle)
}

/**
 * Get articles by blog handle
 */
export function getArticlesByBlog(blogHandle: string): SyncedArticle[] {
  return articles.filter(a => a.blogHandle === blogHandle)
}

/**
 * Get articles by tag
 */
export function getArticlesByTag(tag: string): SyncedArticle[] {
  return articles.filter(a => a.tags.includes(tag))
}

// =============================================================================
// METADATA
// =============================================================================

export const contentSyncedAt = '${content.syncedAt}'
`
}

// =============================================================================
// MAIN SYNC FUNCTION
// =============================================================================

async function syncShopifyContent() {
  console.log('🚀 Starting Shopify content sync...\n')
  
  try {
    // Run all syncs in parallel
    const [navigation, pages, articles] = await Promise.all([
      syncNavigation(),
      syncPages(),
      syncArticles(),
    ])
    
    const content: SyncedContent = {
      navigation,
      pages,
      articles,
      syncedAt: new Date().toISOString(),
    }
    
    // Generate the content file
    const contentFileCode = generateContentFile(content)
    
    // Write to content/shopify-content.ts
    const outputPath = path.join(process.cwd(), 'content', 'shopify-content.ts')
    
    // Ensure content directory exists
    const contentDir = path.dirname(outputPath)
    if (!fs.existsSync(contentDir)) {
      fs.mkdirSync(contentDir, { recursive: true })
    }
    
    fs.writeFileSync(outputPath, contentFileCode, 'utf-8')
    
    console.log('\n✅ Shopify content sync complete!')
    console.log(`   Output: ${outputPath}`)
    console.log(`   Synced at: ${content.syncedAt}`)
    
    // Summary
    console.log('\n📊 Summary:')
    console.log(`   - Navigation items: ${navigation.mainMenu.length}`)
    console.log(`   - Footer sections: ${navigation.footerSections.length}`)
    console.log(`   - Pages: ${Object.keys(pages).length}`)
    console.log(`   - Articles: ${articles.length}`)
    
  } catch (error) {
    console.error('\n❌ Error syncing Shopify content:', error)
    process.exit(1)
  }
}

// Run if this file is executed directly
syncShopifyContent()
