-- Revert "Paid" status for all vendor payouts to allow re-calculation from scratch
-- This does NOT touch fulfillment status
BEGIN;

-- 1. Temporarily disable the immutability trigger for cleanup
DROP TRIGGER IF EXISTS trg_protect_ledger_immutability ON collector_ledger_entries;

-- 2. Clear Payout Tracking
-- This makes all line items "Pending" in the admin/vendor dashboards
DELETE FROM "public"."vendor_payout_items";
DELETE FROM "public"."vendor_payouts";

-- 3. Reset Financial Ledger for Payouts
-- We remove earnings and withdrawals so they can be regenerated by the alignment migration
DELETE FROM "public"."collector_ledger_entries" 
WHERE transaction_type IN ('payout_earned', 'payout_withdrawal');

-- 4. Re-install the immutability trigger
CREATE TRIGGER trg_protect_ledger_immutability
BEFORE UPDATE OR DELETE ON collector_ledger_entries
FOR EACH ROW EXECUTE FUNCTION protect_ledger_immutability();

COMMIT;


