-- Curated Instagram profile URLs for Street Collector artists (vendors.instagram_url).
-- Matches on vendor_name (case-insensitive, trimmed). Rows with no matching vendor are skipped.

UPDATE public.vendors AS v
SET
  instagram_url = x.url,
  updated_at = now()
FROM (
  VALUES
    ('Jerome Masi', 'https://www.instagram.com/jerome.masi/'),
    ('Moritz Adam Schmitt', 'https://www.instagram.com/moritz.adam.schmitt/'),
    ('Loreta Isac', 'https://www.instagram.com/loreta_isac/'),
    ('Marc David Spengler', 'https://www.instagram.com/_marcdavid_/'),
    ('Dawal', 'https://www.instagram.com/dawal/'),
    ('Antonia Lev', 'https://www.instagram.com/antonialev/'),
    ('Hedof', 'https://www.instagram.com/hedof/'),
    ('Taloosh', 'https://www.instagram.com/taloosh.studio/'),
    ('Yonil', 'https://www.instagram.com/yonil/'),
    ('Troy Browne', 'https://www.instagram.com/troybrowne/'),
    ('Elfassi', 'https://www.instagram.com/elfassi/'),
    ('Emelio Cerezo', 'https://www.instagram.com/emiliocerezo/'),
    ('Igal Talianski', 'https://www.instagram.com/iigalskii/'),
    ('Carsten Gueth', 'https://www.instagram.com/die_doing/'),
    ('Or Bar El', 'https://www.instagram.com/or_bar_el/'),
    ('Ori Toor', 'https://www.instagram.com/oritoor/'),
    ('My Sunbeam', 'https://www.instagram.com/mysunbeam/'),
    ('Linda Baritski', 'https://www.instagram.com/seasonofvictory/'),
    ('Erezoo', 'https://www.instagram.com/erezoo/'),
    ('Maalavidaa', 'https://www.instagram.com/maalavidaa/'),
    ('Psoman', 'https://www.instagram.com/psoman_ptk/'),
    ('Agus Rucula', 'https://www.instagram.com/agus.rucula/'),
    ('Max Diamond', 'https://www.instagram.com/maxdiamond52/'),
    ('Ezra Baderman', 'https://www.instagram.com/ezrabaderman/'),
    ('Marylou Faure', 'https://www.instagram.com/maryloufaure/'),
    ('Dima Korma', 'https://www.instagram.com/dimakorma/'),
    ('Samme Snow', 'https://www.instagram.com/snowhandsworld/'),
    ('Sancho', 'https://www.instagram.com/bysancho/'),
    ('Alice Bureau', 'https://www.instagram.com/bureau_alice/'),
    ('Alin Mor', 'https://www.instagram.com/alinmor/'),
    ('Beto Val', 'https://www.instagram.com/elbetoval/'),
    ('Cokorda Martin', 'https://www.instagram.com/treasurecult.work/'),
    ('Aviv Shamir', 'https://www.instagram.com/avivos_91/'),
    ('Hen Macabi', 'https://www.instagram.com/henmacabi/'),
    ('Refiloe Mnisi', 'https://www.instagram.com/urfavsweatpants/'),
    ('Geometric Bang', 'https://www.instagram.com/geometricbang/'),
    ('Laura Fridman', 'https://www.instagram.com/laura_fridman_art/'),
    ('Cubi Boumclap', 'https://www.instagram.com/cubi_boumclap/'),
    ('Studio Giftig', 'https://www.instagram.com/studiogiftig/'),
    ('Unapaulogetic', 'https://www.instagram.com/unapaulogetic_/'),
    ('Thales Towers', 'https://www.instagram.com/thalestowers/'),
    ('Nia Shtai', 'https://www.instagram.com/nia.shtai.art/'),
    ('Nurit Gross', 'https://www.instagram.com/nurit_gross/'),
    ('Moshe Gilboa', 'https://www.instagram.com/moshegilboa/'),
    ('Eden Kalif', 'https://www.instagram.com/_e_d_e_n_/'),
    ('Tiffany Chin', 'https://www.instagram.com/twkchin/'),
    ('Tiago Hesp', 'https://www.instagram.com/tiagohesp/'),
    ('Yoaz', 'https://www.instagram.com/iamyoaz/'),
    ('TWOONE Hiroyasu Tsuri', 'https://www.instagram.com/t_w_o_o_n_e/'),
    ('S A R G O N', 'https://www.instagram.com/oky.sargon/'),
    ('kymo_one', 'https://www.instagram.com/kymo_one/'),
    ('Tyler Shelton', 'https://www.instagram.com/sheltonartco/'),
    ('saturn_png', 'https://www.instagram.com/saturn_png/'),
    ('Levi Jacobs', 'https://www.instagram.com/levijacobss/'),
    ('Jake Ac art', 'https://www.instagram.com/jack_ac_art/'),
    ('Wuper Kec', 'https://www.instagram.com/wuper_kec/'),
    ('Tania yakunova', 'https://www.instagram.com/anni_tett/'),
    ('Ajax Blyth Piper', 'https://www.instagram.com/ajaxpiper/'),
    ('Raki', 'https://www.instagram.com/raki.official.art/'),
    ('Odsk', 'https://www.instagram.com/odsk_/'),
    ('Kaka chazz', 'https://www.instagram.com/kaka.chazz/'),
    ('Chubby Nida', 'https://www.instagram.com/chubbynida/'),
    ('Lobster Robin', 'https://www.instagram.com/lobster_robin/'),
    ('Crackthetoy', 'https://www.instagram.com/crackthetoy/'),
    ('Mameko Maeda', 'https://www.instagram.com/mameko_maeda/'),
    ('Fredrique mati', 'https://www.instagram.com/frederique.png/'),
    ('Phil Huelz', 'https://www.instagram.com/phil.huelz/'),
    ('Ollie Smither', 'https://www.instagram.com/os.illustration/'),
    ('NASCA Uno', 'https://www.instagram.com/nasca_one/'),
    ('Animalitoland', 'https://www.instagram.com/animalitoland/'),
    ('Thibaud HEREM', 'https://www.instagram.com/thibaudherem/'),
    ('Mathew Gagnon', 'https://www.instagram.com/mattjgag/'),
    ('Rik Lee', 'https://www.instagram.com/rikleeillustration/'),
    ('paola delfin', 'https://www.instagram.com/paola_delfin/'),
    ('Wotto Artist', 'https://www.instagram.com/wotto76/'),
    ('Yippie Hey', 'https://www.instagram.com/yippiehey/'),
    ('Keya Tama', 'https://www.instagram.com/keyatama/'),
    ('Woizo', 'https://www.instagram.com/woizoner/'),
    ('Thomas Stary', 'https://www.instagram.com/tomasstary.studio/'),
    ('Vivaladybug', 'https://www.instagram.com/vivalaladybug/'),
    ('Iain Mcarthur', 'https://www.instagram.com/iain.macarthur/'),
    ('Igor Mikutski', 'https://www.instagram.com/igor.mikutski/'),
    ('Got Mikutski', 'https://www.instagram.com/igor.mikutski/')
) AS x(name text, url text)
WHERE lower(trim(v.vendor_name)) = lower(trim(x.name));
